### ISSUE TITLE
 Error when PORT=80 npm start 

### ISSUE THREAD

**Issue by nonjene** [steven-aerts/msgwall#1]
{ [Error: ENOENT: no such file or directory, lstat 'db.json'] errno: -2, code: 'ENOENT', syscall: 'lstat', path: 'db.json' }
module.js:341
    throw err;
    ^

Error: Cannot find module 'express/node_modules/connect'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/rean/Downloads/wall/msgwall/app.js:14:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by steven-aerts** [comment]
Do you also get this problem when using a non privileged port like PORT 8080?

**Comment by nonjene** [comment]
yes, I test other several port and it is the same error,  and also the same if just use 'npm start'

**Comment by steven-aerts** [comment]
Found the problem should be fixed with 7f646d5.

I was bitten by npm/npm#3697.
